micronaut:
  server:
    port: ${PORT:5096}
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    intercept-url-map:
      - access: isAnonymous()
        pattern: /swagger-ui/**
      - access: isAnonymous()
        pattern: /swagger/**
      - access: isAnonymous()
        pattern: /health/**
      - access: isAnonymous()
        pattern: /api/user/**
      - access: isAnonymous()
        pattern: /api/auth/**
datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/authenticationdb`}
    username: ${DB_USER:`root`}
    password: ${DB_PASSWORD:`root`}
    driverClassName: org.postgresql.Driver
    dialect: POSTGRES
netty:
  default:
    allocator:
      max-order: 3
jwk:
  primary: '{
    "p": "4yqY2K1y4y9pcRWgwYESY2FB49gnT5dXiQGjUpBjKQIIVjQGh1gv1wQXrfKCOv6GJtn5-eFQWoxJmEpKKDoYuo9CA_5y2yCKg5dw6YOx21LidcyN1hjbLAoOFWVhCgzXZUsDgKW_Imk7eij5wDN0wst70bsZ0IoZZrBrmo25bMU",
    "kty": "RSA",
    "q": "0cMH7dLkScKmb0RtFjijxK_4iUxatqMFbd90rW23qBlnKABMRis5Sd0_gPCyNVdkgqDmH4OUWWD36-xmQZP5zfRJ5K1TyFQLdFB9LppHme9fsycRQoCXJYcW_NcifVgRwAj8riaOPx4rAd9zUjyKnRwKqoaYLLlwUaqCFRWJwZ8",
    "d": "C90GnV53piaRXbVYDD3sPHN_XEdYcvSflq92k5kE3B8Z6R28hbTELla4_eikIeywZ7e6XdYDMIl-N7HM_IkgGAK4fiT8F_9HSzlbj5W5RYM-YkXmxYr8d_74G4jhKrqaBu4fFLKQyzXAiQpC9h0p0zt_oVkk99lQTee7FfdcT8shp3UrGgWLVX67peXOwJwmG5LSUTPC_rMHm9DV2iwiN3eFyEAgnHKas7eysodEhmNGU8lobQiTOCPIo_0YS1muIpZ3lhUMJkdoAp33h6GbsRDHjbfqUT8hARFWrWSyIwK7v4IKmbGA37RtDa4eS1EcL_CUrQsvfvaDhkvlwrLyeQ",
    "e": "AQAB",
    "use": "sig",
    "kid": "iF-XIvn3z3s6Zg1rZSXmoPiGB_ghYV8iyFaKcY639hM",
    "qi": "3NDN7k50Bp5QkPopXjNUAqXYSP-Uotn1Sro1PcIAuBVCDV08QoEtuGYqY2BR9HkfaGgrKks0njaL0dPLTluP7TeQ_yw2zZKVKx5nR9dAvtLpu16cAWen1h15r4XB7QgTCWNN7gYcAk14A_eH4obe4bFhKmd2mX3V-59-VgU6Qc0",
    "dp": "TP3u9-ExgxZaol02Mt9QICaiclqcWDlvDZxkgmM1eHyb3rubStv0uudEL0x2HxCM3zYZpztaRJYvi1ICeEfYgcJ0GW5v9xy8VYVKW5qq-S7KWiqOF_YssmxmAZJupT1c85PNCBklAsCvy-N_YkkOVccpnBfR1AA6Q7efgK5wHhE",
    "alg": "RS256",
    "dq": "w_uk_N99zCzBtFQKWCizWqHPZPiiCOJnwDB3o1JPtg-GAinFGgpojErbem1pE82Da0lJuUgG4ztmaFeHct3_GB6Wq8IF9bYQvaw2ScR8AadVkt19ktTyY23EXJfk8ZfHfdTnwQ7k-LQHGsjbxooqOIBqtsjqhV79QlA9GdX1z6E",
    "n": "uiLXRIZn3Bk4lfQ3vyfOIm1y5rs32hExqYaawYXR29Zy3fapfQuTloR2sTjwZ_6r_8NUfUvA6DNn1Vg8NJeK4w-JZkH14uk3_JuY2UiOYvNOmlc3L7qAB5C1E13Amq0_CWLbtNbYNdglrexD7hyOdSQmyTHYtscyBkDnSEkx5d0lLsQsQEXaVOx17uOns4Pxv8Wqfky3QYkMoIX92RX_uQ1i2yTUC4tlyaWI30e_b_OnZmOTM0-6KSJuEyA4T8GZ_1Lr8_NkmAtaRk_rOsnLt1jvjihCxoVFoLuj5stzw5e9lRNfYhi1QtZhr4H4O57_3oB0okbUZNFlTF4nL5gTWw"
  }'
  secondary: '{
    "p": "7zYN13GkfqK2Xccpi_prPdlHIyhzfee8nAJQ37Irov5stAhgz6MR8A0Kxc_w7w8QVdpb3pbLBoAy7vUN_y4lV7Gg7EYTuv6nVp6cHCeBH1B_EwQDaUkCEokhLgF5NB4-0NKvlzJuajBAYWDIg_nB42TtokDw7AmDaaGyngZzwZU",
    "kty": "RSA",
    "q": "6nIkP6JoXJznS0h69strFHhUo0erVypYOkxIPu4s_qoMerePYjYArEBot0Qw3OuoM2DaXWbPc3o8E1J9xqqB4RsAXbHXj3pbHSV5psZH3VNE3AqkC5RhbzKhr1q6pqfVZWbclEk9N__Uu_XHru2vv6eSc_-7Wbi5uxCWvIoFUP0",
    "d": "d1Z27bw7s1yeuKb9UbOmVA-4x42TzKNP2hqg2GIJl7j4EwuXHxkYBMacqYmpr1Hg7V67byPWsuMdCxHFrMsQiTrEITpE8SMePZCLLinhEMglKHqRb1Bnn3aVi2srAl4kPP67BUz9hCJNvp4J9mQX3LvXU91wFoUrnF2AxZLHQFpjN8J1lCYZyWR2gv8pBy3kpk0aupL4wWIC9f4cBD6WKYShIDBmFVawIzlHiJWm0oM5MgKmWTs5E_p3Ham9brYby8hmZiEn9-Sohv1JwSSFlC6U_g2iVBpyT_rs8Jh4do9ecxbELlu7_CrSm7t9uqF_cmqItnkarcPZyyQVrv-RcQ",
    "e": "AQAB",
    "use": "sig",
    "kid": "d6mPnmqbmg3PzW2f77ZSny4KVaW_5oMVq2mukkZ--gY",
    "qi": "koMQNlflbYFYbq7Xs3qUXXG8R6WK_NbQ55hPhvGRpPK9aVofRTmHyWmeqwDrfBOXTRVPeKo2DL3dHTgZ7Uex7U40LSz3i1arr98k-UYcAPZ5F-KlGXXVisBRQHUL5oLDRN-MH-azgcnVlFQiRVUVkDE1J5OUrfgaANPuO-5yxC8",
    "dp": "2qaOAF_f--C-0Pk7ALflTqNMYtaWun8X54I2akJxoIru0aDW3PQxcTp6nlVz5Q_f3pm5X7x113tXExTrtlR3zbCPZ2imoEYkrwhLqXByliz9-mOwuowBWO__ZA30u67pu_bYiVuPkYCJWHkez4N7tl6K18SEczw-4k7q9YbwSAE",
    "alg": "RS256",
    "dq": "TZo8j2e1vboeAVhbg2dv6VWvRmDJwU995sYrP9FcyWsGOHScHHkdneawAsGqnuXORjtv7GzEjEfQrOCoS2NTHGzwoRLl9FMe57Xo36BQV11htKg9Bqw12DXdOQsCL3nsc-UpbFgV0Hx5MUI4t5lrjDfujUEABcHUkKv8CSpyeg0",
    "n": "2xIQmCfSZEM36zejErcYlg3CZhWM5eKePPRBC5KW-93WZVkKFGjFflvd1wshZp3FUv9_JGZ3ugb71cyezj9_paxbU1j3ulvhZoZP241K36lrwhJ4lMLyz-wSoSFIOg_dqSCMOtQHNRj10SyKilZAJ5vP1vXpGLnvtHU0nnCZiDnOmdSbzCIfyg33ecQiNwwQgf6QzmXyONDPvRzqpDyu4a3xHAGXu-wbhEfyUW2fUlbtRV1J0m7UsiDmRZKxdpzQTr5CfkP6eiH4ZjZksBc1riR5SJj9JDY2b_RgqKi-en-4wXgWNWeLGPoqZmAUbftJHRuDFs1WaHkZ7uY5ps3gQQ"
  }'
  kid: "iF-XIvn3z3s6Zg1rZSXmoPiGB_ghYV8iyFaKcY639hM"
  kid2: "d6mPnmqbmg3PzW2f77ZSny4KVaW_5oMVq2mukkZ--gY"
  expirationToken: 7200
  expirationRefreshToken: 24
